# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

deployment_type = ENV['DEPLOYMENT_TYPE'] || 'origin'
origin_os = ENV['ORIGIN_OS'] || 'centos'
rhsm_pool = ENV['RHSM_POOL'] || 'Employee SKU'
sync_type = ENV['SYNC_TYPE'] || ''

NETWORK_BASE = '192.168.50'
INTEGRATION_START_SEGMENT = 20

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#  if Vagrant.has_plugin?("vagrant-cachier")
#    config.cache.scope = :machine
#  end

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false

  config.vm.box = box_name

  # Configure eth0 via script, will disable NetworkManager and enable legacy network daemon:
  # config.vm.provision "shell", path: "provision/setup.sh", args: [NETWORK_BASE]
  config.vm.provision "shell", inline: <<-SHELL
    #!/bin/bash
    set -xe
    sed -i -e "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
    systemctl restart sshd
    # FIXME, sometimes eth1 does not come up on Vagrant on latest fc26
    sudo ifup eth1
  SHELL

  config.vm.provider "libvirt" do |libvirt, override|
    libvirt.cpus = 1
    libvirt.cpu_mode = "host-model"
    libvirt.memory = 1024
    libvirt.driver = 'kvm'

    provider_name = 'libvirt'
  end

  # Suppress the default sync in both CentOS base and CentOS Atomic Host
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder '.', '/home/vagrant/sync', disabled: true

  config.vm.define "master" do |master|
    master.vm.network :private_network, ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT}"
    master.vm.hostname = "master.openshift.test"
  end

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.network :private_network, ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT + i}"
      node.vm.hostname = "node-#{i}.openshift.test"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "master" => "master.openshift.test",
      "nodes" => [
        "node-1.openshift.test",
        "node-2.openshift.test"
      ]
    }
    ansible.playbook = "install.yaml"
  end

end
